# Generated by Django 5.1.7 on 2025-07-09 08:08

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='registrationdate',
            new_name='registration_date',
        ),
        migrations.AddField(
            model_name='book',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='available_copies',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phonenumber',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,13}$', message='Enter a valid phone number(10-13digits)')]),
        ),
    ]
