# Generated by Django 5.1.7 on 2025-07-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_rename_registrationdate_member_registration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='returndate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
