# Generated by Django 5.2.3 on 2025-07-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_alter_book_available_copies_alter_book_total_copies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='returndate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
