# Generated by Django 5.1.7 on 2025-07-24 05:28

import library_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_alter_borrowedbook_returndate'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='due_date',
            field=models.DateTimeField(default=library_app.models.default_due_date),
        ),
        migrations.AlterField(
            model_name='member',
            name='registration_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
